// vue-frontend/src/views/Dashboard/Profile.vue
<template>
  <div class="row">
    <div class="col-md-6 col-sm-12 mx-auto">
      <div class="card" v-if="isAuth">
        <div class="card-body">
          <h3 class="card-text">User</h3>
          <p><span class="form-label">Username </span>{{ user.username }}</p>
          <p><span class="form-label">Name </span>{{ user.name }}</p>
          <p><span class="form-label">Email </span>{{ user.email }}</p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { computed } from "vue";
import { useStore } from "vuex";
export default {
  setup() {
    const store = useStore();
    const user = computed(() => store.getters["auth/user"]);
    const isAuth = computed(() => store.getters["auth/isAuth"]);

    return {
      user,
      isAuth,
    };
  },
};
</script>

// rc-frontend/src/views/Dashboard/Profile.jsx
import { connect } from "react-redux";

const Profile = ({ user }) => {
  return (
    <div className="row">
      <div className="col-md-6 col-sm-12 mx-auto">
        <div className="card">
          <div className="card-body">
            <p>
              <span className="form-label">Name </span>
              {user.name}
            </p>
            <p>
              <span className="form-label">Email </span>
              {user.email}
            </p>
            <p>
              <span className="form-label">Username </span>
              {user.username}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

const mapStateToProps = (state) => ({ ...state.auth });
const mapActionsToProps = {};

export default connect(mapStateToProps, mapActionsToProps)(Profile);
