// rc-frontend/src/views/Auth/Login.jsx
import { useState } from "react";
import { connect } from "react-redux";
import { Link, Redirect } from "react-router-dom";
import Input from "../../components/utils/Forms/Input";
import { loginUser } from "../../store/reducer/auth/actions";
import LodingButtonContent from "../../components/utils/LodingButtonContent";

const Login = ({ loginUser, isAuth, authLoading }) => {
  const [user, setUser] = useState({
    username: "",
    password: "",
  });

  const onChange = (e) => setUser({ ...user, [e.target.name]: e.target.value });

  const onSubmit = (e) => {
    e.preventDefault();
    loginUser(user);
  };

  if (!isAuth) {
    return (
      <div className="row">
        <div className="col-md-6 col-sm-12 mx-auto">
          <div className="card">
            <div className="card-body">
              <form onSubmit={onSubmit}>
                <h3 className="card-title">Login</h3>
                <Input
                  name="username"
                  label="Username"
                  onChange={onChange}
                  value={user.username}
                />
                <Input
                  type="password"
                  name="password"
                  label="Password"
                  onChange={onChange}
                  value={user.password}
                />
                <div className="form-group pt-4">
                  <button className="btn btn-primary w-100" type="submit">
                    {authLoading ? <LodingButtonContent /> : "Login"}
                  </button>
                </div>
                <div className="form-group pt-2">
                  <Link className="btn btn-light w-100" to="/auth/register">
                    Need an account? Register now.
                  </Link>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    );
  } else {
    return <Redirect to="/auth/register" />;
  }
};

const mapStateToProps = (state) => ({
  ...state.auth,
});

const mapActionsToProps = {
  loginUser,
};

export default connect(mapStateToProps, mapActionsToProps)(Login);

// vue-frontend/src/views/Auth/Login.vue
<template>
  <div class="row col-md-6 col-sm-12 mx-auto">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Login</h3>
        <form @submit.prevent="loginNow">
          <div class="form-group py-1">
            <label for="username" class="form-label">Username</label>
            <input
              type="text"
              id="username"
              class="form-control"
              placeholder="Username"
              v-model="user.username"
            />
          </div>
          <div class="form-group py-1">
            <label for="password" class="form-label">Password</label>
            <input
              id="password"
              type="password"
              class="form-control"
              placeholder="Password"
              v-model="user.password"
            />
          </div>
          <div class="form-group py-1">
            <button
              :disable="authLoading"
              class="btn btn-primary w-100"
              type="submit"
            >
              Login
            </button>
          </div>
          <div class="form-group py-1">
            <RouterLink to="/auth/register" class="btn btn-light w-100">
              Need an account? Register Now
            </RouterLink>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { useStore } from "vuex";
import { ref, computed } from "vue";

export default {
  setup() {
    const user = ref({
      username: "",
      password: "",
    });

    const store = useStore();
    const authLoading = computed(() => store.getters["auth/isAuth"]);
    const loginNow = () => store.dispatch("auth/loginUser", user.value);

    return {
      user,
      loginNow,
      authLoading,
    };
  },
};
</script>
