// rc-auth-ft/src/views/Auth/Register.jsx
import { useState } from "react";
import { connect } from "react-redux";
import { registerUser, logoutUser } from "../../store/reducers/Auth/actions";

const Register = ({ registerUser, isAuth, logoutUser }) => {
  const [user, setUser] = useState({
    username: "",
    password: "",
    email: "",
    name: "",
  });

  const onChange = (e) => setUser({ ...user, [e.target.name]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("USERER", user);
    registerUser(user);
  };

  const resetFields = () =>
    setUser({
      username: "",
      password: "",
      email: "",
      name: "",
    });

  return (
    <div className="row py-5">
      {isAuth && (
        <button className="btn btn-primary" onClick={logoutUser}>
          Logout
        </button>
      )}
      <div className="col-md-6 col-sm-12 mx-auto">
        <div className="card">
          <div className="card-body">
            <form onSubmit={handleSubmit}>
              <div className="form-group mt-3">
                <label htmlFor="name" className="text-primary">
                  Name
                </label>
                <input
                  id="name"
                  type="text"
                  name="name"
                  onChange={onChange}
                  value={user.name}
                  placeholder="Name"
                  className="form-control"
                />
              </div>
              <div className="form-group mt-3">
                <label htmlFor="username" className="text-primary">
                  Username
                </label>
                <input
                  type="text"
                  id="username"
                  name="username"
                  onChange={onChange}
                  value={user.username}
                  placeholder="Username"
                  className="form-control"
                />
              </div>
              <div className="form-group mt-3">
                <label htmlFor="password" className="text-primary">
                  Password
                </label>
                <input
                  id="password"
                  type="password"
                  name="password"
                  onChange={onChange}
                  value={user.password}
                  placeholder="Password"
                  className="form-control"
                />
              </div>
              <div className="form-group mt-3">
                <label htmlFor="email" className="text-primary">
                  Email
                </label>
                <input
                  id="email"
                  type="email"
                  name="email"
                  onChange={onChange}
                  value={user.email}
                  placeholder="Email"
                  className="form-control"
                />
              </div>
              <div className="form-group mt-3">
                <button className="btn btn-primary" type="submit">
                  Submit
                </button>
                &nbsp;&nbsp;
                <button
                  className="btn btn-secondary"
                  onClick={resetFields}
                  type="button"
                >
                  Reset
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

const mapStateToProps = (state) => ({
  isAuth: state.auth.isAuth,
});

const mapActionsToProps = {
  registerUser,
  logoutUser,
};

export default connect(mapStateToProps, mapActionsToProps)(Register);

// vue-frontend/src/views/Auth/Register.vue
<template>
  <div class="row col-md-6 col-sm-12 mx-auto">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Register</h3>
        <form @submit.prevent="registerNow">
          <div class="form-group py-1">
            <label for="username" class="form-label">Username</label>
            <input
              type="text"
              id="username"
              class="form-control"
              placeholder="Username"
              v-model="user.username"
            />
          </div>
          <div class="form-group py-1">
            <label for="name" class="form-label">Name</label>
            <input
              type="text"
              id="name"
              class="form-control"
              placeholder="Name"
              v-model="user.name"
            />
          </div>
          <div class="form-group py-1">
            <label for="password" class="form-label">Password</label>
            <input
              id="password"
              type="password"
              class="form-control"
              placeholder="Password"
              v-model="user.password"
            />
          </div>
          <div class="form-group py-1">
            <label for="email" class="form-label">Email</label>
            <input
              id="email"
              type="email"
              class="form-control"
              placeholder="Email"
              v-model="user.email"
            />
          </div>
          <div class="form-group py-1">
            <button
              :disabled="authLoading"
              class="btn btn-primary w-100"
              type="submit"
            >
              Register
            </button>
          </div>
          <div class="form-group py-1">
            <RouterLink to="/auth/login" class="btn btn-light w-100">
              Already have an account? Login Now
            </RouterLink>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { useStore } from "vuex";
import { ref, computed } from "vue";

export default {
  setup() {
    const user = ref({
      username: "",
      password: "",
      email: "",
      name: "",
    });

    const store = useStore();
    const authLoading = computed(() => store.getters["auth/isAuth"]);

    const registerNow = () => store.dispatch("auth/registerUser", user.value);

    return {
      user,
      authLoading,
      registerNow,
    };
  },
};
</script>
