// vue-frontend/src/views/Auth/Login.vue
<template>
  <div class="row col-md-6 col-sm-12 mx-auto">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Login</h3>
        <form @submit.prevent="loginNow">
          <div class="form-group py-1">
            <label for="username" class="form-label">Username</label>
            <input
              type="text"
              id="username"
              class="form-control"
              placeholder="Username"
              v-model="user.username"
            />
          </div>
          <div class="form-group py-1">
            <label for="password" class="form-label">Password</label>
            <input
              id="password"
              type="password"
              class="form-control"
              placeholder="Password"
              v-model="user.password"
            />
          </div>
          <div class="form-group py-1">
            <button
              :disable="authLoading"
              class="btn btn-primary w-100"
              type="submit"
            >
              Login
            </button>
          </div>
          <div class="form-group py-1">
            <RouterLink to="/auth/register" class="btn btn-light w-100">
              Need an account? Register Now
            </RouterLink>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { ref, computed } from "vue";
import { dispatchers, getters } from "@/services";

export default {
  setup() {
    const user = ref({
      username: "",
      password: "",
    });

    const authLoading = computed(() => getters("auth", "isAuth"));
    const loginNow = () => dispatchers("auth", "loginUser", user.value);

    return {
      user,
      loginNow,
      authLoading,
    };
  },
};
</script>

// rc-auth-ft/src/views/Auth/Login.jsx
import { useState } from "react";
const Login = () => {
  const [user, setUser] = useState({
    username: "",
    password: "",
  });

  const onChange = (e) => setUser({ ...user, [e.target.name]: e.target.value });

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log("USERER", user);
  };

  const resetFields = () =>
    setUser({
      username: "",
      password: "",
    });

  return (
    <div className="row py-5">
      <div className="col-md-6 col-sm-12 mx-auto">
        <div className="card">
          <div className="card-body">
            <form onSubmit={handleSubmit}>
              <div className="form-group mt-3">
                <label htmlFor="username" className="text-primary">
                  Username
                </label>
                <input
                  type="text"
                  id="username"
                  name="username"
                  onChange={onChange}
                  value={user.username}
                  placeholder="Username"
                  className="form-control"
                />
              </div>
              <div className="form-group mt-3">
                <label htmlFor="password" className="text-primary">
                  Password
                </label>
                <input
                  id="password"
                  type="password"
                  name="password"
                  onChange={onChange}
                  value={user.password}
                  placeholder="Password"
                  className="form-control"
                />
              </div>
              <div className="form-group mt-3">
                <button className="btn btn-primary" type="submit">
                  Submit
                </button>
                &nbsp;&nbsp;
                <button
                  className="btn btn-secondary"
                  onClick={resetFields}
                  type="button"
                >
                  Reset
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;
