// vue-frontend/src/views/Auth/Register.vue
<template>
  <div class="row col-md-6 col-sm-12 mx-auto">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Register</h3>
        <form @submit.prevent="registerNow">
          <div class="form-group py-1">
            <label for="username" class="form-label">Username</label>
            <input
              type="text"
              id="username"
              class="form-control"
              placeholder="Username"
              v-model="user.username"
            />
          </div>
          <div class="form-group py-1">
            <label for="name" class="form-label">Name</label>
            <input
              type="text"
              id="name"
              class="form-control"
              placeholder="Name"
              v-model="user.name"
            />
          </div>
          <div class="form-group py-1">
            <label for="password" class="form-label">Password</label>
            <input
              id="password"
              type="password"
              class="form-control"
              placeholder="Password"
              v-model="user.password"
            />
          </div>
          <div class="form-group py-1">
            <label for="email" class="form-label">Email</label>
            <input
              id="email"
              type="email"
              class="form-control"
              placeholder="Email"
              v-model="user.email"
            />
          </div>
          <div class="form-group py-1">
            <button
              :disabled="authLoading"
              class="btn btn-primary w-100"
              type="submit"
            >
              Register
            </button>
          </div>
          <div class="form-group py-1">
            <RouterLink to="/auth/login" class="btn btn-light w-100">
              Already have an account? Login Now
            </RouterLink>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>
import { useStore } from "vuex";
import { ref, computed } from "vue";

export default {
  setup() {
    const user = ref({
      username: "",
      password: "",
      email: "",
      name: "",
    });

    const store = useStore();
    const authLoading = computed(() => store.getters["auth/isAuth"]);

    const registerNow = () => store.dispatch("auth/registerUser", user.value);

    return {
      user,
      authLoading,
      registerNow,
    };
  },
};
</script>

// rc-frontend/src/views/Auth/Register.jsx
import { useState } from "react";
import { connect } from "react-redux";
import { Link } from "react-router-dom";
import Input from "../../components/utils/Forms/Input";
import { registerUser } from "../../store/reducer/auth/actions";

const Register = ({ registerUser }) => {
  const [user, setUser] = useState({
    username: "",
    password: "",
    name: "",
    email: "",
  });

  const onChange = (e) => setUser({ ...user, [e.target.name]: e.target.value });

  const onSubmit = (e) => {
    e.preventDefault();
    registerUser(user);
  };

  return (
    <div className="row">
      <div className="col-md-6 col-sm-12 mx-auto">
        <div className="card">
          <div className="card-body">
            <form onSubmit={onSubmit}>
              <h3 className="card-title">Register</h3>
              <Input
                name="name"
                label="Name"
                value={user.name}
                onChange={onChange}
              />
              <Input
                name="username"
                onChange={onChange}
                value={user.username}
                label="Username"
              />
              <Input
                type="password"
                name="password"
                label="Password"
                onChange={onChange}
                value={user.password}
              />
              <Input
                type="email"
                name="email"
                label="Email"
                onChange={onChange}
                value={user.email}
              />
              <div className="form-group pt-4">
                <button className="btn btn-primary w-100" type="submit">
                  Register
                </button>
              </div>
              <div className="form-group pt-2">
                <Link className="btn btn-light w-100" to="/auth/login">
                  Already have an account? Login now.
                </Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

const mapStateToProps = (state) => ({ ...state.auth });

const mapActionsToProps = {
  registerUser,
};

export default connect(mapStateToProps, mapActionsToProps)(Register);
